{ "branches": ["master", "next"],
  "plugins": [
    [
        "@semantic-release/commit-analyzer",
      {
        "preset": "jshint"
      }
    ],
    [
        "@semantic-release/release-notes-generator",
      {
        "preset": "jshint"
      }
    ],
    [
      "semantic-release-replace-plugin",
      {
        "replacements": [
          {
            "files": ["version/version.go"],
            "from": 'Version   =.*',
            "to":   'Version   = "${nextRelease.version}"',
            "results": [
              {
                "file": "version/version.go",
                "hasChanged": true,
                "numMatches": 1,
                "numReplacements": 1
              }
            ],
            "countMatches": true
          },
          {
            "files": ["README.md"],
            "from": "# 基于 chain33 区块链开发 框架 开发的 bityuan 系统（.*）",
            "to":   "# 基于 chain33 区块链开发 框架 开发的 bityuan 系统（v${nextRelease.version}）",
            "results": [
              {
                "file": "README.md",
                "hasChanged": true,
                "numMatches": 1,
                "numReplacements": 1
              }
            ],
            "countMatches": true
          },
        ]
      }
    ],
    [
      "@semantic-release/changelog",
      { "changelogFile": "CHANGELOG.md", "changelogTitle": "changelog" },
    ],
    # "@semantic-release/npm", #Default 3
    # "@semantic-release/github", #Default 4
    [
      "@semantic-release/github",
      {"assets": ["build/*.tar.gz","build/*.zip"]}
    ],
    [
      "@semantic-release/git",
      {
        "assets": ["version/version.go","CHANGELOG.md","README.md"],
        "message": "chore(release): ${nextRelease.version} \n\n${nextRelease.notes}"
      }
    ],
    [
      "@semantic-release/exec", {
      "prepareCmd": "make linux-action-amd64 VERSION=${nextRelease.version}"
    }
    ]
  ]
}
